# Generated by Django 4.2.5 on 2023-09-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
