# Generated by Django 4.2.5 on 2023-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_lesson_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='myapp.product'),
        ),
    ]
